import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Installed agent/editor tooling: not our source, already gitignored.
      ".agents/**",
      ".claude/**",
      // Generated by `npm run cf-typegen`; regenerating would undo any edit.
      "worker-configuration.d.ts",
      ".wrangler/**",
    ],
  },
];

export default eslintConfig;
