import { Resend } from "resend";
import { contactSchema } from "../src/lib/contact-schema";
import { profile } from "../src/lib/content";

/**
 * Cloudflare Worker fronting the statically exported site.
 *
 * The site itself is pure static assets, served by the ASSETS binding. The only
 * dynamic surface is POST /api/contact, which used to be a Next route handler
 * and now lives here — `output: "export"` cannot emit route handlers.
 *
 * Requests that match a static asset never reach this code; Workers serves the
 * asset first and only invokes the Worker for what is left over.
 */

/**
 * `Env` is generated by `npm run cf-typegen` (wrangler types) from the bindings
 * in wrangler.jsonc, so the two can never drift. CONTACT_FROM and CONTACT_TO
 * are optional overrides set as secrets rather than declared bindings, so they
 * are added here.
 */
type WorkerEnv = Env & {
  CONTACT_FROM?: string;
  CONTACT_TO?: string;
};

const json = (body: unknown, status = 200, headers: HeadersInit = {}) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", ...headers },
  });

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function clientKey(req: Request) {
  // CF-Connecting-IP is set by Cloudflare's edge and cannot be spoofed by the
  // client, unlike X-Forwarded-For.
  return (
    req.headers.get("cf-connecting-ip") ??
    req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
    "unknown"
  );
}

async function handleContact(req: Request, env: WorkerEnv): Promise<Response> {
  if (!env.RESEND_API_KEY) {
    console.error("[contact] RESEND_API_KEY is not set");
    return json(
      { error: "Email isn't configured yet. Please use the address below instead." },
      503,
    );
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return json({ error: "Malformed request." }, 400);
  }

  // Server-side validation is the real gate; the client copy is only UX.
  const parsed = contactSchema.safeParse(body);
  if (!parsed.success) {
    return json(
      { error: parsed.error.issues[0]?.message ?? "Please check the form and try again." },
      400,
    );
  }

  const { name, email, message, company } = parsed.data;

  // Honeypot tripped: report success and send nothing. Telling a bot it failed
  // just teaches it which field to leave blank next time.
  if (company) return json({ ok: true });

  /**
   * Cloudflare's native rate limiter, which works correctly across isolates and
   * colos. The old in-memory Map could not: Workers instances are ephemeral and
   * distributed, so a per-instance counter rate limits almost nothing.
   *
   * The binding only supports 10s or 60s windows, so the previous 5-per-hour
   * rule becomes 3-per-minute. Still stops rapid-fire spam, paired with the
   * honeypot above.
   */
  const { success } = await env.CONTACT_LIMITER.limit({ key: clientKey(req) });
  if (!success) {
    return json(
      { error: "That's a few messages in a row. Please try again in a minute." },
      429,
      { "Retry-After": "60" },
    );
  }

  const resend = new Resend(env.RESEND_API_KEY);

  /**
   * `from` must be on a domain verified in Resend. The onboarding@resend.dev
   * fallback needs no setup but ONLY delivers to the Resend account owner's own
   * address, so it is fine for testing and wrong for production.
   */
  const from = env.CONTACT_FROM ?? "Portfolio <onboarding@resend.dev>";
  const to = env.CONTACT_TO ?? profile.email;

  const { data, error } = await resend.emails.send({
    from,
    to: [to],
    subject: `Portfolio enquiry from ${name}`,
    replyTo: email,
    text: `${message}\n\n---\nFrom: ${name} <${email}>`,
    html: `
      <div style="font-family:system-ui,sans-serif;line-height:1.6">
        <p style="white-space:pre-wrap">${escapeHtml(message)}</p>
        <hr style="border:none;border-top:1px solid #e5e0d8;margin:24px 0" />
        <p style="color:#555">
          From <strong>${escapeHtml(name)}</strong>
          &lt;<a href="mailto:${encodeURIComponent(email)}">${escapeHtml(email)}</a>&gt;
        </p>
      </div>
    `,
  });

  if (error) {
    // Log the real reason; return something a visitor can act on.
    console.error("[contact] resend error:", error);
    return json(
      { error: "Couldn't send that just now. Please use the address below instead." },
      502,
    );
  }

  return json({ ok: true, id: data?.id });
}

export default {
  async fetch(req: Request, env: WorkerEnv): Promise<Response> {
    const url = new URL(req.url);

    if (url.pathname === "/api/contact") {
      if (req.method !== "POST") {
        return json({ error: "Method not allowed." }, 405, { Allow: "POST" });
      }
      return handleContact(req, env);
    }

    // Everything else is the statically exported site.
    return env.ASSETS.fetch(req);
  },
} satisfies ExportedHandler<WorkerEnv>;
